plugins {
    id "com.android.application"
}

android {
    namespace "com.uu.harvestcollection.mobile"
    compileSdkVersion 36
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "com.uu.harvestcollection.mobile"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 240
        versionName "2.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

tasks.register("syncWebAssets", Copy) {
    from("../../dist")
    into("src/main/assets/www")
}

tasks.named("preBuild").configure {
    dependsOn("syncWebAssets")
}
