plugins {
    id "com.android.application"
}

android {
    namespace "com.uu.harvestcollection.mobile"
    compileSdkVersion 36
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "com.uu.harvestcollection.mobile"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 250
        versionName "2.5.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    sourceSets {
        main {
            assets.srcDirs = []
        }
    }
}
